// General purpose tags describing what kind of project this ties into
:tags: [flask, webservers]

// Primary language of the starter kit
:language: python

// What is needed for this project (this might better go into language-specific sections,
// unless it requires an external product (for example, another server). For repeated
// requirements it should be possible to use an asciidoc include to include more
// detailed explanations
:requirements: [Flask]

// This text is displayed as the short description of the project
:blurb: Demonstrate exposing Couchbase functionality via a REST API using Flask

// Used to distinguish between example/guide types. We might also add "howto", etc.
:type: starter

// This should eventually go into a common header:
:source-highlighter: highlightjs

= Couchbase Python Flask Gateway

== What this is

This project contains a simple Flask bootstrap sample which exposes various
REST APIs backed by Couchbase functionality. Consumers of this API can retrieve, modify
and query documents using simple HTTP verbs.

== How to use this

Clone this starter kit and set it up for your Couchbase Cluster including the bucket by editing the source.  Then modify it to suit your needs.  To make this your own project you can `rm -rf .git` in the cloned project and then `git init` to make it your own project.

=== Running

[source,sh]
.Running the server
----
$ pip install -r requirements.txt
$ python cbflask.py
# Will show the port the server is running on. This is typically 5000
----

[source,sh]
.Storing a document
----
echo '{"name":"Couchbase", "email":"couchbase@couchbase.com", "company":"Couchbase"}' | curl -XPUT http://localhost:5000/id/user:couchbase --data-binary @-
echo '{"name":"Mark", "email":"markn@couchbase.com", "company":"Couchbase"}' | curl -XPUT http://localhost:5000/id/user:mark --data-binary @-
echo '{"name":"Jimbo", "email":"jimbo@jimbosoft.com", "company":"Jimbosoft"}' | curl -XPUT http://localhost:5000/id/user:jimbo --data-binary @-
----

[source,sh]
.Retrieving a document
----
curl http://localhost:5000/id/user:1234
# {"email": "couchbase@couchbase.com", "name": "Couchbase"}
----

[source]
.Querying for a document
----
curl http://localhost:5000/query/default?company=Couchbase | python -m json.tool
[
    {
        "company": "Couchbase",
        "email": "couchbase@couchbase.com",
        "name": "Couchbase"
    },
    {
        "company": "Couchbase",
        "email": "markn@couchbase.com",
        "name": "Mark"
    }
]
----

=== Where to go from here

This starter kit demonstrates several aspects of constructing N1QL queries in Python, such
as creating an index and iterating over the results. Play around with the resultsets and
queries to see how richer functionality can be acheived.  Look at the Developer Guide samples on Python and N1QL and the N1QL language reference for more details on how to use these Couchbase features.

=== See also
* http://developer.couchbase.com/documentation/server/4.0/developer-guide/creating-documents.html[Developer guide sections on basic operation]
* http://developer.couchbase.com/documentation/server/4.0/developer-guide/querying.html[Developer guide sections on N1QL]
* http://developer.couchbase.com/documentation/server/4.0/n1ql/n1ql-intro/data-access-using-n1ql.html[N1QL Documentation]
